### ISSUE TITLE
Design

### ISSUE THREAD

**Issue by hedi-far** [hedi-far/nextjs-kids-clothing-storage-web-app#13]
#### Part 1: 
- [x] Make layout to apply via CSS - grid & content alignment

Prototype on Figma: https://www.figma.com/file/GcdMIySrnycWC5vC1oKrBj/Layout?node-id=0%3A1

### Part 2:
- Learn about responsive design
- [x] https://www.youtube.com/watch?v=p0bGHP-PXD4&t=1s
- [x] https://learn.upleveled.io/courses/btcmp-l-webfs-gen-0/modules/112-cheatsheet-responsive-design/

### Part 3 
- [x] Re-Watch Bootcamp video about UI design / presentation!
- [x] Which colors, fonts …?
  https://colors.muz.li/
- [x] icons (e.g. bag, box)
- [x] picture on start page
- [x] Style components in Figma!
- Footer:
- [x] https://www.orbitmedia.com/blog/website-footer-design-best-practices/
- [x] https://learn.upleveled.io/courses/btcmp-l-webfs-gen-0/modules/164-cheatsheet-legal/#do-i-need-an-impressum
- [x] https://learn.upleveled.io/courses/btcmp-l-webfs-gen-0/modules/200-free-photos-graphics/
- [x] Think of name!
- [x] Use grid and/or flexbox!
- [ ] CSS Grid Layout Crash Course: https://www.youtube.com/watch?v=jV8B24rSN5o
- [ ] Learn CSS Grid in 20 Minutes: https://www.youtube.com/watch?v=9zBsdzdE4sM
- [ ] CSS Grid Tutorial | CSS Grid Crash Course: https://www.youtube.com/watch?v=EFafSYg-PkI
- [ ] CSS Grid vs Flexbox: https://www.youtube.com/watch?v=RSIclWvNTdQ
- [ ] Flexbox CSS In 20 Minutes: https://www.youtube.com/watch?v=JJSoEo8JSnc
- [ ] Learn Flexbox in 15 Minutes: https://www.youtube.com/watch?v=fYq5PXgSsbE
- [ ] Learn Flexbox In 20 Minutes | Learn HTML & CSS | Flexbox Tutorial: 
https://www.youtube.com/watch?v=FTlczfR82mQ
